### ISSUE TITLE
Hibernate ORM User Guide

### ISSUE THREAD

**Issue by rayzeng27** [zengshuang1989/Apple#9]
日常开发工作中我们在编写业务逻辑的过程中都是通过BDF提供的元数据和API来读写数据实例信息。在BDF之下还有其它的底层的框架，Hibernate和JDBC（PS：再往下还有其它层次的框架，我们从未接触，也不需要太关心），每层框架都是对下层框架能力的封装和增强，提供贴近特定领域的有限API集合，聚焦于解决特定领域的问题（例如提升CRM领域的定制开发效率）。

![image](https://user-images.githubusercontent.com/31339078/31306297-701fbc5e-ab7f-11e7-9f56-eb9392d84bd5.png)

上一次读User Guide还是n年前的3.x时代，现在又来读一次5.x，核心架构和理念变化不大，但添加了很多便捷的能力，例如支持通过注解来进行映射配置；支持将enums直接映射为entity field type（在3.x时还需要自己扩展UserType来实现）；支持JPA规范(Java Persistence API)的各种能力；等等。

User Guide的内容很多，有介绍框架和规范的，有深入性能调优的，有各种配置的详细说明，有些章节要通读，形成自己的见解，有些章节只需要略读，无需深入细节。我们的主要目标是通过阅读学习+动手写代码的方式，对Hibnerate和JPA spec在经验值上达到“熟悉”的程度。

Hibernate提供的很多能力都是JPA spec的一部分，建议在阅读每个章节有提到JPA的，可以把对应的规范部分也阅读下[《JPA Specification 2.1 (Java Persistence API)》](http://download.oracle.com/otndocs/jcp/persistence-2_1-fr-eval-spec/index.html) --- 总共有570+页，不要被吓到了，我们学习的过程中要看很多资料 ：）

我会在自己阅读的基础上，在下面的目录上标注出阅读建议 :smile:
`★★★★★：`精华，要深入学习和理解；
`★★★★☆：`加深印象，能口述出关键功能点；
`★★★☆☆：`留下印象，给出关键提示时能口述出功能点和使用场景；
`★★☆☆☆：`简单了解，大概知道有这个功能点，但不知道细节；
`★☆☆☆☆：`可看可不看，或者是用到时再查阅；

# 已经阅读过的章节，可以打上√ :blush:

**Comment by rayzeng27** [comment]
### 1. Architecture
- [x] 1.1. Overview `★★★★★：精华，先读一遍，留个大概印象，在阅读后面章节时会需要反复回过来看，加深理解！`

### 编码练习
无

**Comment by rayzeng27** [comment]
### 2. Domain Model
- [x] 2.1. Mapping types `★★★★☆`
- [x] 　2.1.1. Value types `★★★☆☆`
- [x] 　2.1.2. Entity types `★★★☆☆`
- [ ] 2.2. Naming strategies `★★★★☆`
- [x] 　2.2.1. ImplicitNamingStrategy `★★★☆☆`
- [x] 　2.2.2. PhysicalNamingStrategy `★★★☆☆`
- [ ] 2.3. Basic Types `★★★☆☆`
- [x] 　2.3.1. Hibernate-provided BasicTypes `★★☆☆☆`
- [x] 　2.3.2. The @Basic annotation `★★★☆☆`
- [x] 　2.3.3. The @Column annotation `★★★☆☆`
- [x] 　2.3.4. BasicTypeRegistry `★★☆☆☆`
- [x] 　2.3.5. Explicit BasicTypes `★★☆☆☆`
- [x] 　2.3.6. Custom BasicTypes `★☆☆☆☆`
- [x] 　2.3.7. Mapping enums `★★★☆☆`
- [x] 　2.3.8. Mapping LOBs `★☆☆☆☆`
- [x] 　2.3.9. Mapping Nationalized Character Data `★☆☆☆☆`
- [x] 　2.3.10. Mapping UUID Values `★★☆☆☆`
- [x] 　2.3.11. UUID as binary `★☆☆☆☆`
- [x] 　2.3.12. UUID as (var)char `★☆☆☆☆`
- [x] 　2.3.13. PostgeSQL-specific UUID `★☆☆☆☆`
- [x] 　2.3.14. UUID as identifier `★★☆☆☆`
- [x] 　2.3.15. Mapping Date/Time Values `★★☆☆☆`
- [x] 　2.3.16. JPA 2.1 AttributeConverters `★☆☆☆☆`
- [x] 　2.3.17. SQL quoted identifiers `★☆☆☆☆`
- [x] 　2.3.18. Generated properties `★★★☆☆`
- [x] 　2.3.19. Column transformers: read and write expressions `★☆☆☆☆`
- [x] 　2.3.20. @Formula `★★☆☆☆`
- [x] 　2.3.21. @Where `★★☆☆☆`
- [ ] 　2.3.22. @WhereJoinTable `★☆☆☆☆`
- [x] 　2.3.23. @Filter `★★☆☆☆`
- [ ] 　2.3.24. @FilterJoinTable `★☆☆☆☆`
- [ ] 　2.3.25. @Filter with @SqlFragmentAlias `★☆☆☆☆`
- [x] 　2.3.26. @Any mapping `★☆☆☆☆`
- [ ] 　2.3.27. @JoinFormula mapping `★☆☆☆☆`
- [ ] 　2.3.28. @JoinColumnOrFormula mapping `★☆☆☆☆`
- [ ] 　2.3.29. @Target mapping `★★☆☆☆`
- [ ] 　2.3.30. @Parent mapping `★★☆☆☆`
- [ ] 2.4. Embeddable types `★★★★☆`
- [x] 　2.4.1. Component / Embedded `★★★★☆`
- [x] 　2.4.2. Multiple embeddable types `★★☆☆☆`
- [x] 　2.4.3. Overriding Embeddable types `★★☆☆☆`
- [x] 　2.4.4. Embeddables and ImplicitNamingStrategy `★★☆☆☆`
- [x] 　2.4.5. Collections of embeddable types `★☆☆☆☆`
- [x] 　2.4.6. Embeddable types as Map key `★☆☆☆☆`
- [x] 　2.4.7. Embeddable types as identifiers `★☆☆☆☆`
- [ ] 2.5. Entity types
- [x] 　2.5.1. POJO Models `★★★★☆`
- [x] 　2.5.2. Prefer non-final classes `★★★☆☆`
- [x] 　2.5.3. Implement a no-argument constructor `★★★☆☆`
- [x] 　2.5.4. Declare getters and setters for persistent attributes `★★★☆☆`
- [x] 　2.5.5. Provide identifier attribute(s) `★★★☆☆`
- [x] 　2.5.6. Mapping the entity `★★★☆☆`
- [x] 　2.5.7. Implementing equals() and hashCode() `★★☆☆☆`
- [ ] 　2.5.8. Mapping the entity to a SQL query `★★☆☆☆`
- [ ] 　2.5.9. Define a custom entity proxy `★☆☆☆☆`
- [ ] 　2.5.10. Dynamic entity proxies using the @Tuplizer annotation `★☆☆☆☆`
- [ ] 　2.5.11. Define a custom entity persister `★☆☆☆☆`
- [x] 　2.5.12. Access strategies `★★☆☆☆`
- [ ] 2.6. Identifiers `★★★★☆`
- [x] 　2.6.1. Simple identifiers `★★★★☆`
- [x] 　2.6.2. Composite identifiers `★★★★☆`
- [x] 　2.6.3. Composite identifiers with @EmbeddedId `★★☆☆☆`
- [x] 　2.6.4. Composite identifiers with @IdClass `★★☆☆☆`
- [x] 　2.6.5. Composite identifiers with associations `★★☆☆☆`
- [x] 　2.6.6. Generated identifier values `★★★☆☆`
- [x] 　2.6.7. Interpreting AUTO `★★☆☆☆`
- [x] 　2.6.8. Using sequences `★★☆☆☆`
- [x] 　2.6.9. Using IDENTITY columns `★★☆☆☆`
- [x] 　2.6.10. Using table identifier generator `★★☆☆☆`
- [x] 　2.6.11. Using UUID generation `★★☆☆☆`
- [x] 　2.6.12. Optimizers `★☆☆☆☆`
- [ ] 　2.6.13. Using @GenericGenerator `★☆☆☆☆`
- [x] 　2.6.14. Derived Identifiers `★☆☆☆☆`
- [ ] 　2.6.15. @RowId `★☆☆☆☆`
- [ ] 2.7. Associations `★★★☆☆`
- [x] 　2.7.1. @ManyToOne `★★★☆☆`
- [x] 　2.7.2. @OneToMany `★★★☆☆`
- [x] 　2.7.3. @OneToOne `★★★☆☆`
- [x] 　2.7.4. @ManyToMany `★★★☆☆`
- [ ] 　2.7.5. @NotFound association mapping `★★☆☆☆`
- [ ] 2.8. Collections `★★★☆☆`
- [x] 　2.8.1. Collections as a value type `★★★☆☆`
- [x] 　2.8.2. Collections of value types `★★★☆☆`
- [x] 　2.8.3. Collections of entities `★★★☆☆`
- [x] 　2.8.4. Bags `★★☆☆☆`
- [x] 　2.8.5. Ordered Lists `★★☆☆☆`
- [x] 　2.8.6. Sets `★★☆☆☆`
- [x] 　2.8.7. Sorted sets `★★☆☆☆`
- [x] 　2.8.8. Maps `★★☆☆☆`
- [x] 　2.8.9. Arrays `★★☆☆☆`
- [x] 　2.8.10. Arrays as binary `★☆☆☆☆`
- [x] 　2.8.11. Collections as basic value type `★☆☆☆☆`
- [ ] 　2.8.12. Custom collection types `★☆☆☆☆`
- [x] 2.9. Natural Ids `★★★☆☆`
- [x] 　2.9.1. Natural Id Mapping `★★★☆☆`
- [x] 　2.9.2. Natural Id API `★★☆☆☆`
- [x] 　2.9.3. Natural Id - Mutability and Caching `★★☆☆☆`
- [x] 2.10. Dynamic Model `★★☆☆☆`
- [x] 　2.10.1. Dynamic mapping models `★★☆☆☆`
- [x] 2.11. Inheritance `★★★★☆`
- [x] 　2.11.1. MappedSuperclass `★★★☆☆`
- [x] 　2.11.2. Single table `★★★☆☆`
- [x] 　2.11.3. Joined table `★★★☆☆`
- [x] 　2.11.4. Table per class `★★★☆☆`
- [x] 　2.11.5. Implicit and explicit polymorphism `★★☆☆☆`
- [x] 2.12. Immutability `★★☆☆☆`
- [x] 　2.12.1. Entity immutability `★★☆☆☆`
- [x] 　2.12.2. Collection immutability `★★☆☆☆`

### 编码练习
- [x] 1. 用枚举类型定义所有的常量，并通过注解跟字段绑定起来；
- [x] 2. 将Account作为基类，扩展若干具体的子类，父类和子类都有对应的表；
- [x] 3. 为每张表都添加两个公共字段：createdDatetime和lastUpdatedDatetime，精确到毫秒，要自动设置；
- [x] 4. 为每张表的主键添加自动生成策略；
- [x] 5. 为Account表添加只读的瞬态字段totalFlowIn和totalFlowOut，类型为double，在加载Account实例时从Record表计算得到；
- [x] 6. 为Account表添加只读的瞬态字段balance，根据totalFlowIn和totalFlowOut计算得到；
- [x] 7. 为Record和Account建立One2One关系；
--------------------------------------------
**2017.11.05 CodeReview后补充**
- [x] 8. 是否可以提取一个Entity的基类，放置id，createdDatetime和lastUpdatedDatetime等等公共字段？
- [x] 9. 文件中的tab缩进，统一替换成空格缩进；
- [x] 10. 文件的编码修改成utf8，否则在github上直接查看会有乱码；
- [x] 11. 类名单词拼写有误：AccoutController；
- [x] 12. 类名和作用不相符：HelloController.java；
- [x] 13. 疑问：account.balance，为何从两个金额字段的相减，改成HQL语句？
--zxy：还没有找到更好的办法。查询语句Hibernate: select account0_.id as id1_0_0_, account0_.create_time as create_t2_0_0_, account0_.update_time as update_t3_0_0_, account0_.name as name4_0_0_, account0_.remark as remark5_0_0_, account0_.role_id as role_id6_0_0_, account0_.type as type7_0_0_, ((select sum(t.money) from record t where t.flowin_acct_id = account0_.id)-(select sum(t.money) from record t where t.flowout_acct_id = account0_.id)) as formula0_0_, (select sum(t.money) from record t where t.flowin_acct_id = account0_.id) as formula1_0_, (select sum(t.money) from record t where t.flowout_acct_id = account0_.id) as formula2_0_ from account account0_ where account0_.id=?
- [x] 14. 疑问：数据库表的字段update_time为何默认值是：'2017-11-14 16:00:00'？
--zxy：预置数据时方便用的，以后再删除吧。

以下两项为CodeReivew过程中记录，发现在后续编码中已经体现，可忽略：
Entity中的Type字段，类型要从现有的String修改为具体的Enum；
--zxy：都已修改。
createdDatetime和lastUpdatedDatetime的类型是java.sql.Date，不够精确，要达到秒的级别；
--zxy：已修改成timestamp

--------------------------------------------

**2017.11.09 CodeReview后补充**
- [x] 15. Account的子类可以直接把type属性固化，无需外部设置；
在子类的get,set方法中直接固化了，是还有其它更好的方法吗？
- [x] 16. Account表里已经有的字段，其子类表不需要再重复出来，两个表通过ID联系即可；
- [x] 17. DAO类的重复代码比较多，后续可消除，此任务体现在第5章里 ：）

**Comment by rayzeng27** [comment]
### 3. Bootstrap
- [x] 3.1. JPA Bootstrapping `★★☆☆☆`
- [x] 　3.1.1. JPA-compliant bootstrapping `★☆☆☆☆`
- [x] 　3.1.2. Externalizing XML mapping files `★☆☆☆☆`
- [x] 3.2. Native Bootstrapping `★★☆☆☆`
- [x] 　3.2.1. Building the ServiceRegistry `★☆☆☆☆`
- [x] 　3.2.2. Event Listener registration `★☆☆☆☆`
- [x] 　3.2.3. Building the Metadata `★☆☆☆☆`
- [x] 　3.2.4. Building the SessionFactory `★☆☆☆☆`

### 编码练习
无

**Comment by rayzeng27** [comment]
### 4. Schema generation
- [x] 4.1. Importing script files `★☆☆☆☆`
- [x] 4.2. Database objects `★☆☆☆☆`
- [ ] 4.3. Database-level checks `★☆☆☆☆`
- [ ] 4.4. Default value for database column `★☆☆☆☆`
- [ ] 4.5. Columns unique constraint `★☆☆☆☆`
- [ ] 4.6. Columns index `★☆☆☆☆`

### 编码练习
无

**Comment by rayzeng27** [comment]
### 5. Persistence Contexts
- [x] 5.1. Accessing Hibernate APIs from JPA `★☆☆☆☆`
- [x] 5.2. Bytecode Enhancement `★☆☆☆☆`
- [x] 　5.2.1. Capabilities `★☆☆☆☆`
- [x] 　5.2.2. Performing enhancement `★☆☆☆☆`
- [x] 5.3. Making entities persistent `★★★☆☆`
- [x] 5.4. Deleting (removing) entities `★★★☆☆`
- [x] 5.5. Obtain an entity reference without initializing its data `★★★☆☆`
- [x] 5.6. Obtain an entity with its data initialized `★★★☆☆`
- [x] 5.7. Obtain an entity by natural-id `★★★☆☆`
- [x] 5.8. Modifying managed/persistent state `★★★☆☆`
- [ ] 　5.8.1. Dynamic updates `★★★☆☆`
- [x] 5.9. Refresh entity state `★★★☆☆`
- [x] 　5.9.1. Refresh gotchas `★★★☆☆`
- [x] 5.10. Working with detached data `★★☆☆☆`
- [x] 　5.10.1. Reattaching detached data `★★☆☆☆`
- [x] 　5.10.2. Merging detached data `★★☆☆☆`
- [x] 5.11. Checking persistent state `★★★☆☆`
- [x] 5.12. Evicting entities `★★★☆☆`
- [ ] 5.13. Cascading entity state transitions `★★★☆☆`

### 编码练习
- [x] 1. 写一个DAO的抽象基类，通过IOC注入persistence context相关的类，并封装常用的CDRU操作，其子类可以通过泛型来指定具体要操作的entity type，基类中不包含任何跟事务有关的语句；

![2017-11-22_172830](https://user-images.githubusercontent.com/31339078/33119801-12ae9f54-cfab-11e7-9609-282711188d6f.png)

--------------------------------------------

**2017.11.24 CodeReview后补充**
- [x] 1. 需要为每一种类型的Account写一个DAO吗？是否只提供一个统一的AccountDao？
- [ ] 2. BaseDao是否可以不包含事务的代码？如何支持在一次事务请求中通过多个Dao修改多个entity？

**Comment by rayzeng27** [comment]
### 6. Flushing
- [x] 6.1. AUTO flush `★★☆☆☆`
- [x] 　6.1.1. AUTO flush on commit `★★☆☆☆`
- [x] 　6.1.2. AUTO flush on JPQL/HQL query `★★☆☆☆`
- [x] 　6.1.3. AUTO flush on native SQL query `★★☆☆☆`
- [x] 6.2. COMMIT flush `★★☆☆☆`
- [x] 6.3. ALWAYS flush `★★☆☆☆`
- [x] 6.4. MANUAL flush `★★☆☆☆`
- [x] 6.5. Flush operation order `★★☆☆☆`

flush功能本身理解起来不困难，但在复杂的使用场景里能用好不容易，类似于OM的长流程中共享一个事务，其中每个环节可能是由不同的开发人员编码完成，对于同一类entity即有单个读写的操作，也有批量读写的操作，要在适当的时机使用flush，即要保证数据的一致性，也不能损耗太多的性能。

### 编码练习
无

**Comment by rayzeng27** [comment]
### 7. Database access
- [x] 7.1. ConnectionProvider `★☆☆☆☆`
- [x] 7.2. Using DataSources `★☆☆☆☆`
- [x] 7.3. Using c3p0 `★☆☆☆☆`
- [x] 7.4. Using Proxool `★☆☆☆☆`
- [x] 7.5. Using existing Proxool pools `★☆☆☆☆`
- [x] 7.6. Configuring Proxool via XML `★☆☆☆☆`
- [x] 7.7. Configuring Proxool via Properties `★☆☆☆☆`
- [x] 7.8. Using Hikari `★☆☆☆☆`
- [x] 7.9. Using Hibernate’s built-in (and unsupported) pooling `★☆☆☆☆`
- [x] 7.10. User-provided Connections `★☆☆☆☆`
- [x] 7.11. ConnectionProvider support for transaction isolation setting `★☆☆☆☆`
- [x] 7.12. Database Dialect `★☆☆☆☆`

### 编码练习
- [x] 1. 说明下在apple/backend里，hibernate是如何获取到数据库connection的？
在apple/backbend里，hibernate是通过Using DataSources获取到数据库的connection的。
a. 配置的springmvc-servlet.xml中的datasource bean，此org.apache.commons.dbcp2.BasicDataSource类实现了javax.sql.DataSource类的getConnection()方法。
b. 在LocalSessionFactoryBuilder中将datasource设置到hibernate.connection.datasource配置项。
c. StandardServiceRegistryBuilder 注册并应用配置项。
d. 在buildSessionFactory时，使用配置项。

**Comment by rayzeng27** [comment]
### 8. Transactions and concurrency control
- [x] 8.1. Physical Transactions `★★★☆☆`
- [x] 8.2. JTA configuration `★★★☆☆`
- [x] 8.3. Hibernate Transaction API `★★★☆☆`
- [x] 8.4. Contextual sessions `★★★☆☆`
- [x] 8.5. Transactional patterns (and anti-patterns) `★☆☆☆☆`
- [x] 8.6. Session-per-operation anti-pattern `★★★☆☆`
- [x] 8.7. Session-per-request pattern `★★★☆☆`
- [x] 8.8. Conversations `★★★☆☆`
- [x] 8.9. Session-per-application `★★★☆☆`

### 编码练习
- [x] 1. 写一个测试用例(sprint bean)，让hibernate使用jdbc的方式来控制transaction，通过编码来对事务进行控制，同时对多个entity进行查询和修改操作；
- [x] 2. 写一个测试用例(sprint bean)，通过注解的方式来声明事务，同时对多个entity进行查询和修改操作；

**Comment by rayzeng27** [comment]
### 9. JNDI
看看就行...

### 编码练习
无

**Comment by rayzeng27** [comment]
### 10. Locking
- [x] 10.1. Optimistic `★★★☆☆`
- [x] 10.1.1. Mapping optimistic locking `★★★☆☆`
- [x] 10.2. Pessimistic `★★★☆☆`
- [x] 10.3. LockMode and LockModeType `★★☆☆☆`
- [x] 10.4. JPA locking query hints `★☆☆☆☆`
- [x] 10.5. The buildLockRequest API `★☆☆☆☆`
- [x] 10.6. Follow-on-locking `★☆☆☆☆`

数据库锁我们日常编码中用得比较少，了解下乐观锁和悲观锁的概念即可。

### 编码练习
无

**Comment by rayzeng27** [comment]
### 11. Fetching `★★☆☆☆`
- [x]  `★☆☆☆☆` Fetching是指从数据库加载数据的策略，通常是关联查询集合数据时需要加以控制，避免一次加载过多数据，造成服务器压力过大，或者是未真实被使用而造成资源浪费，Fetching属于性能调优的一部分，当前简单了解下原理即可，不用深入；
 
### 12. Batching `★★☆☆☆`
- [x] Batching是指在往数据库批量修改数据时，如何利用底层能力，分批期在服务器和数据库之间同步刷新，避免所有修改点堆积在服务器侧，造成服务器压力过大，Batching也是性能调优的一部分，当前简单了解下原理即可，不用深入；

### 13. Caching `★★☆☆☆`
- [x] Caching是指将从数据库读取出的数据存放在内存中，在下次访问时直接从内存中读取，通过空间换取访问能力，本章节主要了解Hibernate的一线缓存和二级缓存，以及缓存失效策略；Caching也是性能调优的一部分，合理的缓存设置能提高数据库访问的命中率，当前简单了解下即可，不用深入；

### 14. Interceptors and events `★★☆☆☆`
- [x] 拦截器与事件，提供机制让外部能感知Hibernate在读取和操作数据的整个流程中的每个环节。有切入点能做一些业务操作，例如记录日志，更新统计数据等等。

### 15. HQL and JPQL `★★☆☆☆`
- [x] HQL/JPQL是在标准的SQL的基础上，扩展了面向对象的一些语法和实用方法。能直接跟业务逻辑无缝对接上。在直接使用Hibernate的场景里，HQL的使用还是比较频繁的。建议整个章节都粗略看下，留个印象。

### 16. Criteria `★★☆☆☆`
- [x] Criteria是以编程的方式拼装HQL语句，从可读性效果来说，没有HQL来得直观；优点是拼装方式灵活，适合于条件多变的查询场景；

### 编码练习
考虑针对流水记录表提供搜索功能，搜索条件最少包含以下几个：
![image](https://user-images.githubusercontent.com/31339078/33660261-351a4f16-dabe-11e7-8c22-7e39baeed709.png)

其它需求：
1. 多个条件之间是与的关系；
2. 多个条件能形成一个“组”保存到数据库里，后续加载使用，例如：“ZY最近三个月的餐饮费用”；
3. 查询的拼装逻辑用criteria实现；
4. 要考虑扩展性，即新加一种条件的编码代价最小化；
5. 暂时不考虑前端界面，通过测试用例来模拟前端请求；

**Comment by rayzeng27** [comment]
### 17. Native SQL Queries `★☆☆☆☆`
- [x] 直接用原生SQL查询本地数据库，支持本地数据库的专属语法。知道有这个能力即可，不用细看；

### 18. Spatial `★☆☆☆☆`
- [x] 讲述Hibernate如何读取和操作用于记录地理信息的数据，知道有这个能力即可，不用细看；

### 19. Multitenancy `★☆☆☆☆`
- [x] 讲述Hibernate如何支持多租；了解Hibernate支持多租的三种方式，特别是第三种，是我们最常用的，当前Hibernate还在开发中；

### 20. OSGi `★☆☆☆☆`
- [x] OSGi是Java动态化模块化系统，如果做过Eclipse上的Plugin开发的话，对这个会比较熟悉；知道有这个能力即可，不用细看；

###  21. Envers `★☆☆☆☆`
- [x] 审计能力，针对entity的每一次更新操作做一次修订记录，后续可以查询entity的所有修订记录做回溯；知道有这个能力即可，不用细看；

###  22. Database Portability Considerations `★☆☆☆☆`
- [x] 讲述Hibernate对不同数据库产品的适配能力，涉及的差异点主要有主键生成方式，数据库功能函数，数据库类型映射等等；典型的数据库产品有Oracle，Mysql，SqlServer；简单了解；

###  23. Configurations `★☆☆☆☆`
- [x] 配置参考手册，简单看下标题种类即可；

###  24. Mapping annotations `★☆☆☆☆`
- [x] 注解参考手册，简单看下标题种类即可；

###  25. Performance Tuning and Best Practices `★☆☆☆☆`
- [x] 性能调优和最佳实践，简单了解；

###  26. Legacy Bootstrapping `☆☆☆☆☆`
讲述如何兼容老的启动方式，不用看了；

###  27. Migration `☆☆☆☆☆`
新旧API之间的映射参考，不用看了；

###  28. Legacy Domain Model `☆☆☆☆☆`
不知道是啥，不用看了...；

###  29. Legacy Hibernate Criteria Queries `☆☆☆☆☆`
旧的Criterria查询方式，不用看了；

###  30. Legacy Hibernate Native Queries `☆☆☆☆☆`
旧的原生SQL查询方式，不用看了；

**Comment by rayzeng27** [comment]
![2017-12-13_151135](https://user-images.githubusercontent.com/31339078/33931778-06116178-e02c-11e7-914e-9c47ec1448ce.png)

**Comment by zengshuang1989** [comment]
改了配置，用声明式管理事务时，也还是会报错的。
```
<property name="current_session_context_class">thread</property>
十二月 16, 2017 1:31:14 上午 org.apache.catalina.core.StandardWrapperValve invoke
严重: Servlet.service() for servlet [springmvc] in context with path [/backend] threw exception [Request processing failed; nested exception is org.hibernate.HibernateException: save is not valid without active transaction] with root cause
org.hibernate.HibernateException: save is not valid without active transaction
	at org.hibernate.context.internal.ThreadLocalSessionContext$TransactionProtectionWrapper.invoke(ThreadLocalSessionContext.java:351)
	at com.sun.proxy.$Proxy58.save(Unknown Source)
	at edu.zxy.apple.dao.BaseDaoImpl.add(BaseDaoImpl.java:22)
	at edu.zxy.apple.bean.TestAnnotationTransationBean.testOperateDatabase(TestAnnotationTransationBean.java:25)
	at edu.zxy.apple.bean.TestAnnotationTransationBean$$FastClassBySpringCGLIB$$6e32f63d.invoke(<generated>)

<property name="current_session_context_class">org.springframework.orm.hibernate3.SpringSessionContext</property>
严重: Servlet.service() for servlet [springmvc] in context with path [/backend] threw exception [Request processing failed; nested exception is org.hibernate.HibernateException: No CurrentSessionContext configured!] with root cause
org.hibernate.HibernateException: No CurrentSessionContext configured!
	at org.hibernate.internal.SessionFactoryImpl.getCurrentSession(SessionFactoryImpl.java:454)
	at edu.zxy.apple.dao.BaseDaoImpl.add(BaseDaoImpl.java:18)
	at edu.zxy.apple.bean.TestAnnotationTransationBean.testOperateDatabase(TestAnnotationTransationBean.java:25)
	at edu.zxy.apple.bean.TestAnnotationTransationBean$$FastClassBySpringCGLIB$$6e32f63d.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720)
```
配置错了，应该是hibernate4，但还是会报错
```
<property name="current_session_context_class">org.springframework.orm.hibernate4.SpringSessionContext</property>
十二月 18, 2017 12:07:22 上午 org.springframework.transaction.interceptor.TransactionInterceptor completeTransactionAfterThrowing
严重: Application exception overridden by rollback exception
java.lang.IllegalStateException: Already value [org.springframework.orm.hibernate5.SessionHolder@5f1c59f6] for key [org.hibernate.internal.SessionFactoryImpl@be6d396] bound to thread [http-nio-8080-exec-2]
	at org.springframework.transaction.support.TransactionSynchronizationManager.bindResource(TransactionSynchronizationManager.java:190)
	at org.springframework.orm.hibernate4.SpringSessionContext.currentSession(SpringSessionContext.java:129)
	at org.hibernate.internal.SessionFactoryImpl.getCurrentSession(SessionFactoryImpl.java:456)
	at edu.zxy.apple.dao.BaseDaoImpl.add(BaseDaoImpl.java:18)
	at edu.zxy.apple.bean.TestAnnotationTransationBean.testOperateDatabase(TestAnnotationTransationBean.java:25)
	at edu.zxy.apple.bean.TestAnnotationTransationBean$$FastClassBySpringCGLIB$$6e32f63d.invoke(<generated>)
	

十二月 18, 2017 12:07:22 上午 org.apache.catalina.core.StandardWrapperValve invoke
严重: Servlet.service() for servlet [springmvc] in context with path [/backend] threw exception [Request processing failed; nested exception is java.lang.IllegalStateException: No value for key [org.hibernate.internal.SessionFactoryImpl@be6d396] bound to thread [http-nio-8080-exec-2]] with root cause
java.lang.IllegalStateException: No value for key [org.hibernate.internal.SessionFactoryImpl@be6d396] bound to thread [http-nio-8080-exec-2]
	at org.springframework.transaction.support.TransactionSynchronizationManager.unbindResource(TransactionSynchronizationManager.java:210)
	at org.springframework.orm.hibernate5.HibernateTransactionManager.doCleanupAfterCompletion(HibernateTransactionManager.java:649)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.cleanupAfterCompletion(AbstractPlatformTransactionManager.java:1016)
```

看到一篇文章http://blog.csdn.net/irelandken/article/details/7193123

> spring 整合hibernate管理事务后，由Spring的TransactionManager管理事务后, currentSession是绑定到SpringSessionContext的，而不是thread。
此时hibernate.current_session_context_class应该是SpringSessionContext，而它又会在使用LocalSessionFactoryBean时自动的设置。
所以就不需要你去设置current_session_context_class


不设置current_session_context_class，果然ok了。 使用jdbc管理事务时，还是要加上此配置的，否则会报如下的错。
```
十二月 18, 2017 12:13:24 上午 org.apache.catalina.core.StandardWrapperValve invoke
严重: Servlet.service() for servlet [springmvc] in context with path [/backend] threw exception [Request processing failed; nested exception is org.hibernate.HibernateException: Could not obtain transaction-synchronized Session for current thread] with root cause
org.hibernate.HibernateException: Could not obtain transaction-synchronized Session for current thread
	at org.springframework.orm.hibernate5.SpringSessionContext.currentSession(SpringSessionContext.java:133)
	at org.hibernate.internal.SessionFactoryImpl.getCurrentSession(SessionFactoryImpl.java:456)
	at edu.zxy.apple.bean.TestJDBCTransationBean.testOperateDatabase(TestJDBCTransationBean.java:28)
	at edu.zxy.apple.controller.TestJDBCTransationController.testOper(TestJDBCTransationController.java:20)
```

**Comment by zengshuang1989** [comment]
问题1、对前台提供的接口queryRecord,，入参是List<BaseCondVO> condList，而从前台请前过来json转换成的condList变量为List<LinkedHashMap>类型。在for循环处理时报错。
严重: Servlet.service() for servlet [springmvc] in context with path [/backend] threw exception [Request processing failed; nested exception is java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to edu.zxy.apple.condition.vo.BaseCondVO] with root cause
java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to edu.zxy.apple.condition.vo.BaseCondVO
	at edu.zxy.apple.condition.manage.CondProcessManage.execute(CondProcessManage.java:44)
	at edu.zxy.apple.dao.RecordDaoImpl.queryRecord(RecordDaoImpl.java:27)
	at edu.zxy.apple.controller.RecordController.queryRecord(RecordController.java:81)
	at edu.zxy.apple.controller.RecordController$$FastClassBySpringCGLIB$$c8502200.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)	

此问题通过通过将json对象重新转一遍，但是也不是很好，而且超过基类的属性，就会报错。就有第二个问题
ObjectMapper  mapper=new ObjectMapper();
BaseCondVO pojo = mapper.convertValue(linkedHashMap , BaseCondVO.class);

问题2：json的多子类继承的object转换
使用JsonTypeInfo和JsonSubTypes注解，没很理解怎么使用。
按如用例http://blog.csdn.net/java_huashan/article/details/46428971又解决不了，前台过来的json里不会是简洁的。。

这个问题。。。。。

2018/1/26
使用JsonDeserialize，实现json转换基类对象时子类对象实例化。BaseCondVODeserialize执行中能找到json串中的type，
但还是有2个问题：
1）jsonparse需要回原点，没找到回原点的方法。。。
2）在json转子类对象时，也会执行基类对象上的设置的BaseCondVODeserialize。好像要循环死了。。

2018/1/30
暂时没有好的办法解决，直接用字符串转了
